2023-02-23 17:46:51,601 INFO    MainThread:19448 [wandb_setup.py:_flush():68] Configure stats pid to 19448
2023-02-23 17:46:51,601 INFO    MainThread:19448 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Thomas\.config\wandb\settings
2023-02-23 17:46:51,601 INFO    MainThread:19448 [wandb_setup.py:_flush():68] Loading settings from c:\Users\Thomas\AudioHandling\wandb\settings
2023-02-23 17:46:51,601 INFO    MainThread:19448 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-23 17:46:51,601 INFO    MainThread:19448 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-23 17:46:51,601 INFO    MainThread:19448 [wandb_init.py:_log_setup():492] Logging user logs to c:\Users\Thomas\AudioHandling\wandb\run-20230223_174651-dd3f2n9u\logs\debug.log
2023-02-23 17:46:51,601 INFO    MainThread:19448 [wandb_init.py:_log_setup():493] Logging internal logs to c:\Users\Thomas\AudioHandling\wandb\run-20230223_174651-dd3f2n9u\logs\debug-internal.log
2023-02-23 17:46:51,602 INFO    MainThread:19448 [wandb_init.py:_jupyter_setup():438] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001EA89230A00>
2023-02-23 17:46:51,602 INFO    MainThread:19448 [wandb_init.py:init():532] calling init triggers
2023-02-23 17:46:51,602 INFO    MainThread:19448 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-02-23 17:46:51,602 INFO    MainThread:19448 [wandb_init.py:init():554] re-initializing run, found existing run on stack: rglewslk
2023-02-23 17:46:51,603 INFO    MainThread:19448 [wandb_run.py:_finish():1854] finishing run tnapier/a2o-swav-lightly/rglewslk
2023-02-23 17:46:51,603 INFO    MainThread:19448 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-02-23 17:46:51,603 INFO    MainThread:19448 [wandb_run.py:_restore():2066] restore
2023-02-23 17:46:51,603 INFO    MainThread:19448 [wandb_run.py:_restore():2072] restore done
2023-02-23 17:49:21,467 WARNING MsgRouterThr:19448 [router.py:message_loop():77] message_loop has been closed
2023-02-23 17:49:23,191 INFO    MainThread:19448 [wandb_run.py:_restore():2066] restore
2023-02-23 17:49:23,191 INFO    MainThread:19448 [wandb_run.py:_restore():2072] restore done
2023-02-23 17:49:23,223 ERROR   MainThread:19448 [wandb_init.py:init():1160] error
Traceback (most recent call last):
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\wandb_run.py", line 2092, in _atexit_cleanup
    self._on_finish()
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\wandb_run.py", line 2326, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\lib\mailbox.py", line 288, in wait
    on_probe(probe_handle)
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\wandb_run.py", line 2291, in _on_probe_exit
    result = handle.wait(timeout=0)
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\lib\mailbox.py", line 271, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\wandb_init.py", line 1133, in init
    run = wi.init()
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\wandb_init.py", line 567, in init
    self._wl._global_run_stack[-1].finish()
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\wandb_run.py", line 371, in wrapper
    return func(self, *args, **kwargs)
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\wandb_run.py", line 334, in wrapper
    return func(self, *args, **kwargs)
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\wandb_run.py", line 1845, in finish
    return self._finish(exit_code, quiet)
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\wandb_run.py", line 1860, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\wandb_run.py", line 2103, in _atexit_cleanup
    self._backend.cleanup()
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\backend\backend.py", line 259, in cleanup
    self.interface.join()
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 639, in join
    super().join()
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\interface\interface.py", line 742, in join
    _ = self._communicate_shutdown()
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 552, in _communicate_shutdown
    _ = self._communicate(record)
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 285, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 60, in _communicate_async
    future = self._router.send_and_receive(rec, local=local)
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\interface\router.py", line 94, in send_and_receive
    self._send_message(rec)
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\interface\router_sock.py", line 36, in _send_message
    self._sock_client.send_record_communicate(record)
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\lib\sock_client.py", line 216, in send_record_communicate
    self.send_server_request(server_req)
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Thomas\conda\envs\audiohandling\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
